# Generated by Django 4.1.3 on 2022-11-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('acc_no', models.CharField(max_length=50)),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('color1', models.CharField(max_length=30)),
                ('color2', models.CharField(max_length=30)),
                ('color3', models.CharField(max_length=30)),
                ('color4', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=4)),
            ],
        ),
    ]
