# Generated by Django 4.1.3 on 2023-04-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_color1_accounts_color2_accounts_color3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='pin',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
