# Generated by Django 4.1.3 on 2023-04-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accounts_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='pin',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
