# Generated by Django 4.1.3 on 2023-04-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_accounts_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='acc_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
